#### 异常处理
异常使得我们能够将问题的检测与解决过程分离开来，程序的一部分负责检测问题的出现，然后解决该问题的任务传递给程序的另一部分。检测环节无须知道问题处理模块的所有细节，反之亦然。
##### 抛出异常
在c++语言中，我们通过抛出（throw）一条表达式来引发一个异常，被抛出表达式的类型以及当前的调用链共同决定了哪段处理代码将被用来处理该异常。    
当执行一个throw时，跟在throw后面的语句将不再执行，相反，程序的控制权从throw转移到与之匹配的catch模块。控制权从一处转移到另外一处，这有两个重要的含义：
- 沿着调用链的函数可能会提前退出
- 一旦程序开始执行异常处理代码，则沿着调用链创建的对象将被销毁   

因为跟在throw后面的语句将不再执行，所以throw语句的用法有点类似于return语句，它通常作为条件语句的一部分或者作为某个函数的最后（或者唯一）一条语句。  
###### 栈展开
当抛出一个异常后，程序暂停当前函数的执行过程并立即开始寻找与异常匹配的catch子句，当throw出现在一个try语句块内时，检查与该try块关联的catch子句，如果找到匹配的catch，就使用该catch处理异常，如果这一步没有找到匹配的catch且该try语句嵌套在其他try块中，则继续检查与外层try匹配的catch子句，如果还是找不到匹配的catch，则退出当前函数，在调用当前函数的外层函数中继续寻找。   
上述过程称为栈展开，栈展开过程沿着嵌套函数的调用链不断查找，直到找到了与异常匹配的catch子句为止，或者也可能一直没有找到匹配的catch，则推出主函数后查找过程终止。   
当找不到匹配的catch时，程序将调用标准库函数terminate，负责终止程序的执行过程。
###### 栈展开过程中对象被自动销毁
如果栈展开过程中退出了某个块，编译器将负责确保在这个块中创建的对象能被正确的销毁。如果某个局部对象的类型是类类型，则该对象的析构函数将被自动调用，与往常一样，编译器在销毁内置类型的对象时不需要做任何事情。
###### 析构函数与异常
析构函数总是会被执行，但是函数中负责释放资源的代码却可能被跳过，这一特点对于我们如何组织程序结构有重要影响。如果一个块分配了资源，并且在负责释放这些资源的代码前面发生了异常，则释放资源的代码将不会被执行，另一方面，类对象分配的资源将类的析构函数负责释放，因此，如果我们使用类来控制资源的分配，就能确保无论函数正确结束还是遭遇异常，资源都能被正确的释放。
```
void exercise(int *b, int *e)
{
    vector<int> v(b, e);
    int *p = new int[v.size()];
    ifstream in("ints");
    //此处发生异常
    
    
    delete p;
}
```
上面的例子,资源的释放不会被执行，会造成资源泄露。一种典型的解法使用try...catch语句捕捉异常。还有一种是用类来管理资源。
```
calss Resource
{
public:
    Resource(size_t sz) : p(new int[sz])
    { }
    ~Resource()
    {
        if (p)
            delete p;
    }
private:
    int *p;
};

void exercise(int *b, int *e)
{
    vector<int> v(b, e);
    Resource re(v.size());
    ifstream in("ints");
    //此处发生异常
    
    
    delete p;
}
```
在栈展开过程中，运行类类型的局部对象的析构函数，因为这些析构函数是自动执行的，所以它们不应该抛出异常，一旦在栈展开的过程中析构函数抛出了异常，并且析构函数自身没能捕捉到该异常，则程序终止。
###### 异常对象
异常对象位于由编译器管理的空间中，编译器确保无论最终调用时哪个catch子句都能访问该空间，当异常处理完毕后，异常对象被销毁。   
如我们所知，当一个异常被抛出时，沿着调用链的块将依次推出直至找到与异常匹配的处理代码，如果退出了某个块，则同时释放块中局部对象使用的内存，因此抛出一个指向局部对象的指针几乎肯定是一种错误的行为。   
==当我们抛出一条表达式时，该表达式的静态编译时类型决定了异常对象的类型，读者必须牢记这一点，因为很多情况下程序抛出的表达式来自于某个继承体系==。如果一条throw表达式解引用一个基类指针，而该指针实际指向的是派生类对象，则抛出的对象将被切掉一部分，只有基类部分被抛出。
##### 捕获异常
catch子句的异常声明看起来像是只==包含一个形参的函数形参列表==。像形参列表中一样，如果catch子句无须访问抛出的表达式的话，则我们可以忽略捕获形参的名字。  
声明的类型决定了处理代码所能捕获的异常类型，这个类型必须是==完全类型==，它可以是左值引用，但不能是右值引用。 当进入一个catch语句后，通过异常对象初始化异常声明中的参数，和函数参数类似，如果catch的参数类型是非引用类型，则该参数是异常对象的一个副本，在catch语句内改变该参数实际上改变的是局部副本而非异常对象本身。相反，如果参数是引用类型，则和其他引用参数一样，该参数是异常对象的一个别名，此时改变参数也就是改变异常对象。  
如果catch的参数是基类类型，则我们可以使用其派生类类型的异常对象对其进行初始化，此时，如果catch的参数是非引用类型，则异常对象被切掉一部分，这与将派生类对象以值传递的方式传给一个普通函数差不多，另一方面，如果catch的参数是基类的引用，则该参数以常规方式绑定到异常对象上。    
异常声明的静态类型将决定catch语句所能执行的操作，如果catch的参数是基类类型，则catch无法使用派生类特有的任何成员。==通常情况下，如果catch接受的异常与某个继承体系有关，则最好将该catch的参数定义成引用类型==。  
###### 查找匹配的处理代码
我们最终找到的catch未必是异常的最佳匹配，相反，挑选出来的应该是第一个与异常匹配的catch语句，因此，越是专门的catch越应该置于整个catch列表的前端。   
异常声明匹配规则：
- 允许从非常量向常量的类型转换，也就是说，一条非常量对象的throw语句可以匹配一个接受常量引用的catch语句。  
- 允许从派生类向基类的类型转换
- 数组被转换成指向数组类型的指针，函数被转换成指向该函数类型的指针。   

除此之外，==包括标准算术类型转换盒类类型转换在内==，其他所有转换规则都不能匹配catch的过程中使用。  
== 如果在多个catch语句的类型之间存在着继承关系，则我们应该把继承链最底端的类放在前面，而将继承链最顶端的类放在后面。
###### 重新抛出
一条catch语句通过重新抛出的操作将异常传递给另外一个catch语句，这里的重新抛出仍然是一条throw语句，只不过不包含任何表达式。空的throw语句只能出现在catch语句或catch语句直接或间接调用的函数内。   
==一条重新抛出语句并不指定新的表达式，而是将当前的异常对象沿着调用链向上传递==。
```
catch (my_error &eobj)//引用类型
{
    eobj.status = errCodes::severeErr;//修改了异常对象
    throw;             //异常对象的status成员是severeErr
}
catch (other_error eobj)//非引用类型
{
    eobj.status = errCodes::badErr;//只修改了异常对象的局部副本
    throw;   //异常对象的status成员没有改变
}
```
###### 捕获所有异常的处理代码
为了一次性捕获所有异常，我们使用省略号作为异常声明，这里的处理代码称为捕获所有异常
```
void mainp()
{
    try
    {
        //这里操作将引发一个异常
    }
    catch (...)
    {
        //处理异常的某些特殊操作
        throw;//重新抛出
    }
}
```
==如果catch (...) 与其他几个catch语句一起出现，则catch (...)必须在最后的位置，出现在捕获所有异常语句后面的catch语句将永远不会被匹配。
##### 函数的try语句块与构造函数
构造函数在进入其函数体之前首先执行初始值列表，因为在初始值列表抛出异常时构造函数体内的try语句块还未生效，所以构造函数体内的catch语句无法处理构造函数初始值列表抛出的异常。   
我们必须将构造函数写成函数try语句块的形式，函数try语句块使得一组catch语句既能处理构造函数体（或析构函数体），也能处理构造函数的初始化过程（或析构函数的析构过程）。  
```
template <typename T>
Blob<T>::Blob(std::initializer_list<T> il) try : data(std::make_shared<std::vector<T>> (il)) 
{
    /* 空函数体*/
}
catch (const std::bad_alloc &e)
{
    handle_out_of_memory(e);
}
```
还有一种情况值得注意，在初始化构造函数的参数时也可能发生异常，这样的异常不属于函数try语句块的一部分，函数try语句块只能处理构造函数开始执行后发生的异常，和其他函数调用一样，如果在参数初始化的过程中发生了异常，则该异常属于调用表达式一部分，并将在调用者所在的上下文中处理。
##### noexcept异常说明
对于用户及编译器来说，预先知道某个函数不会抛出异常显然大有裨益，首先，知道函数不会抛出异常有助于简化调用该函数的代码，其次，如果编译器确认函数不会抛出异常，它就能执行某些特殊的优化操作，而这些优化操作并不适用于可能出错的代码。   
```
void recoup(int) noexcept; //不会抛出异常
void alloc(int); //可能会抛出异常
```
对于一个函数来说，noexcept说明==要么出现在该函数的所有声明语句和定义语句中，要么一次也不出现==。该说明应该在函数的尾置返回类型之前，我们也可以在函数指针的声明和定义中指定noexcept，在typedef或类型别名中则不能出现noexcept，在成员函数中，noexcept说明符需要跟在const及引用限定符之后，而在final、override或虚函数=0之前。
###### 违反异常说明
编译器并不会在编译时检查noexcept说明，实际上，一个函数在说明了noexcept的同时又含有throw语句或者调用了可能抛出异常的其他函数，编译器将顺利编译通过，并不会因为这种违反异常说明而报错。
```
//尽管函数明显违反了异常说明，但它仍然可以编译通过
void f() noexvcept   //承诺不会抛出异常
{
    throw exception();
}
```
一旦一个noexcept函数抛出了异常，程序就会调用terminate以确保遵守不在运行时抛出异常的承诺。  
因此noexcept可以用在两种情况下：
- 我们确认函数不会抛出异常
- 我们根本不知道该如何处理异常

==通常情况下，编译器不能也不应该在编译时验证异常说明==。
```
void recoup() noexcept;  //不会抛出异常
void recoup() throw();  //不会抛出异常,早起C++版本，
```
###### 异常说明的实参
noexcept说明符接受一个==可选的实参==，该实参必须能转换为bool类型，如果实参是true，则函数不会抛出异常，如果实参是false，则函数可能会抛出异常。   
```
void recoup(int) noexcept(true);  //不会抛出异常
void recoup(int) noexcept(false);  //可能抛出异常
```
###### noexcept运算符
noexcept运算符是一个一元运算符，它的返回值是一个bool类型的右值常量表达式，用于表示给定的表达式是否会抛出异常，和sizeof类似，noexcept也不会求其运算对象的值。
```
noexcept(recoup(i));//如果recoup不抛出异常，则结果为true，否则为false

void f() noexcept(noexcept(g()));//f和g的异常说明一样
```
###### 异常说明与指针、虚函数与拷贝控制
- 如果我们为某个指针做出了不抛出异常的说明，则该指针将只能指向不抛出异常的函数，相反，如果我们显式或隐式地说明指针可能抛出异常，则该指针可以指向任何函数，即使是承诺了不抛出异常的函数也可以。
```
//recoup 和 pf1 都承诺不会抛出异常
void (*pf1) (int) noexcept = recoup;
//正确 recoup不会抛出异常， pf2可能抛出异常，两者互不干扰
void (*pf2) (int) = recoup;

pf1 = alloc; //错误，allco可能抛出异常，而pf1承诺不会抛出异常
pf2 = alloc;//正确
```
- 如果一个虚函数承诺了它不会抛出异常，则后续派生出来的虚函数也必须做出同样的承诺，与之相反，如果基类的虚函数允许抛出异常，则派生类的对应函数既可以允许抛出异常，也可以不允许抛出异常。
```
class Base
{
public:
    virtual double f1(double) noexcept;
    virtual int f2() noexcept(false);
    virtual void f3();
};

calss Derived: public Base
{
public:
    double f1(double); //错误，Base::f1承诺不会抛出异常
    int f2() noexcept(false); //正确
    void f3() noexcept;//正确
};
```
- 当编译器合成拷贝控制成员时，同时也生成一个异常说明，==如果对所有成员和基类的所有操作都承诺了不会抛出异常，则合成的成员是noexcept的，如果合成成员调用的任意一个函数可能抛出异常，则合成的成员是noexcept(false)。而且
我们定义了一个析构函数但是没有为它提供异常说明，则编译器将合成一个，合成的异常说明将与假设有编译器为类合成的析构函数时所得的异常说明一致==。
##### 异常类层次
```
class exception {};

class bad_cast :      exception {};
class runtime_error : exception {};
class bad_alloc :     exception {};
class logic_error :   exception {};

class overflow_error :  runtime_error {};
class underflow_error : runtime_error {};
class range_error :     runtime_error {};

class domain_error :     logic_error {};
class invalid_argument : logic_error {};
class out_of_range :     logic_error {};
class length_error :     logic_error {};
```
类型exception仅仅定义了拷贝构造函数，拷贝赋值运算符，一个虚析构函数和一个what的虚成员，其中what函数返回一个const char* ,该指针指向null结尾的字符数组，并且确保不会抛出异常。
###### 书店应用程序的异常类
```
//为某个书店应用程序设定的异常类
class out_of_stock:public std::runtime_error
{
public:
    explicit out_of_stock(const std::string &s):
                        std::runtime_error(s) { }
};

class isbn_mismatch : public std::logic_error
{
public:
    explicit isbn_mismatch(const std::string &s) :
                std::logic_error(s) { }
    
    isbn_mismatch(const std::string &s, const std::string &lhs
                const std::string &rhs) :
                std::logic_error(s), left(lhs), right(rhs) { }
    
    const std::string left, right;
};

Sales_data& Sales_data::operator+=(const Sales_data& rhs)
{
    if (isbn() != rhs.isbn())
        throw isbn_mismatch("wrong isbns", isbn(), rhs.isbn());
    units_sold += rhs.units_sold;
    revenue += rhs.revenue;
    
    return *this;
}

//使用之前设定的书店程序异常类
Sales_data item1, item2, sum;
while (cin >> item1 >> item2)
{
    try
    {
        sum = item1 + item2;
    }
    catch (const isbn_mismatch &e)
    {
        cerr << e.what() << ": left isbn(" << e.left
             << ") right isbn (" << e.right << ")" << endl;
    }
}

```
#### 命名空间













































































































































